# Generated by Django 3.2.11 on 2022-03-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('pwd', models.CharField(max_length=40)),
                ('favstocks', models.CharField(max_length=15000)),
            ],
        ),
    ]
