# Generated by Django 3.2.11 on 2022-04-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220405_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='diversity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='risk_percentage',
            field=models.CharField(max_length=10),
        ),
    ]
